### ISSUE TITLE
Using tdrop with emacsclient in BSPWM

### ISSUE THREAD

**Issue by ykhurshid** [noctuid/dotfiles#10]
When I try creating a new emacsclient frame with tdrop, not only does it not create the new frame in float but running the hotkey again simply creates a new frame instead of toggling the visibility of the existing frame.
What would be the idiomatic way to launch a new emacsclient frame under tdrop?

**Comment by ykhurshid** [comment]
Sorry, accidentally posted this issue here instead of the tdrop repository where it should be, is it possible if you could move it there? (I don't know how to move issues)

**Comment by noctuid** [comment]
It is working for me on the latest commit; please try now. If you have any issues, please make a new issue on the tdrop repository.
