### ISSUE TITLE
Did you swap keys in evil-mode?

### ISSUE THREAD

**Issue by ghost** [noctuid/dotfiles#12]
I use colemak layout too and use evil mode.
Did you swap keys like hnei?

I'd like to know what keys are swapped.
Could you give me some sample code?

**Comment by noctuid** [comment]
Yes. The general swaps I prefer are these:

`n` as `j`
`e` as `k`
`i` as `l`
`j` as `e`
`k` as `n`
`l` as `i`

I picked these based on discussion on the Colemak forum (this is what at least some other people use). I added a [key translation feature](https://github.com/emacs-evil/evil-collection#key-translation) to evil-collection to allow for making swaps like this for a lot of modes all at once.

My personal setup is a bit more complicated. For example, I don't use `h` as left or `i` for right in text modes. I use `h` for help and `i` for insert and use a separate modifier + `h` and `i` for horizontal movement. I have more notes in my config about this. I can post some of it as an example if you want, but the previous link is a more simple/straightforward example.

**Comment by neeasade** [comment]
(colemak-dh) For a slightly less intrusive but also more inconvienent mapping, I do:

noremap e k
noremap n j
noremap k n

The downside to this is then that 3 out of the 4 directional binds are all handled by my right index finger

**Comment by ghost** [comment]
Thank you for answering!!!

I use the layout which puts k on the home row and h on the bottom row.  I think you have the same layout. Do you use h for  navigation because it is easier to type h  that k?

About your config notes:  I really would like to see them!

**Comment by noctuid** [comment]
I added some of my config. [Here](https://github.com/noctuid/dotfiles/blob/master/emacs/.emacs.d/awaken.org#colemak-swapschanges) are some notes about the swaps. [Here](https://github.com/noctuid/dotfiles/blob/master/emacs/.emacs.d/awaken.org#colemak-swaps) is where I do some general swaps.

**Comment by ghost** [comment]
Oh I can see your emacs config finally!!! Thanks for taking time to publish your config!
