### ISSUE TITLE
What replaced wm_action?

### ISSUE THREAD

**Issue by mvrozanti** [noctuid/dotfiles#17]
I saw your [reddit post](https://old.reddit.com/r/bspwm/comments/372t29/how_to_resize_windows/), I was just wondering how you bind wm_action and then I see you don't bind it at all. What happened?

**Comment by noctuid** [comment]
I'm still binding it (see [here](https://github.com/noctuid/dotfiles/blob/master/remap/.config/sxhkd/wm_sxhkdrc)) though I only use bspwm, so I don't really need it anymore. I split my sxhkdrc to be able to load different config combinations.
