### ISSUE TITLE
Suggestion: EXWM

### ISSUE THREAD

**Issue by QiangF** [noctuid/dotfiles#3]
Hello,
Can you please try a window manager in emacs?
https://github.com/ch11ng/exwm/
Thank you!

**Comment by noctuid** [comment]
I've tried exwm in the past, but I don't personally feel that using emacs for window management has any advantages over other window managers. I personally like bspwm much better.

**Comment by QiangF** [comment]
I think the advantages are

1 EXWM manage windows as buffers, with emacs search and filtering you can manage
more windows easier.
2 emacs is keyboard driving, EXWM can even simulate emacs hot keys in other
applications.
3 emacs has a lot of useful packages, all in plain emacs lisp, it create an
ecosystem that is thriving. It has alternatives for many other utilities, fore
example I use counsel-linux-app as my system application laucher.

I have just used linux and emacs for less than two years. So there surely are
more advantages than I know.

**Comment by noctuid** [comment]
I don't ever have enough different windows open to make the ability to search through them useful. Often I don't have more than a browser and emacs open. There's also rofi which can be used similarly for other window managers.

xdotool, xsendkey, etc. can simulate keys to windows regardless of the window manager.

If I wanted to do a lot of work extending/customizing a window manager, I definitely could see the value in EXWM. As-is I don't really like it that much, and bspwm pretty much already has everything I want, so I don't have the need for extensibility in elisp personally. The other great things about emacs (like dealing with text) don't really have good applications to window management. I like to do as much as possible in emacs and keep management of other windows simple. Bspwm's scriptability/rules system is very good as well.

**Comment by ninrod** [comment]
Hi @noctuid, is there any specifics on why did you choose bspwm over i3? I'm looking forward to use a window manager over a desktop env. and was curious about your choice.

**Comment by noctuid** [comment]
One of the main things that I like about bspwm is that it is controlled entirely through `bspc` (commandline program), which allows you to use whatever hotkey daemon you want and makes it easily scriptable in whatever language you want. Bspwm has a nice rules system and a lot of useful query-related commands that make it pretty simple to do more complicated customization. I've found that the keybinding systems of a lot of window managers are pretty limited in what they support, but i3's is pretty good. I used i3 for a little, and i3 does have `i3-msg` which can be used similarly to `bspc` (though it isn't as powerful and isn't the primary method of interacting with i3).

That said, i3 is probably better if you want a WM that just works well and don't want to do anything more complicated. It comes with a panel (i3bar) unlike bspwm and its tabbed and stacked layouts are pretty nice. If you're interested in further customization, you can always try both out and see which you like better.

**Comment by ninrod** [comment]
Ah, ok thanks. I only use a browser and a terminal and emacs. I think I'd want the simplest WM manager that I can find.
