### ISSUE TITLE
full emacs configuration

### ISSUE THREAD

**Issue by ninrod** [noctuid/dotfiles#4]
Hi @noctuid. I was studying your emacs configuration and noticed that the emacs/.emacs.d directory is very, very small. the awaken.org file is just a few lines long. Is your full emacs configuration elsewhere or even undisclosed? thanks

**Comment by noctuid** [comment]
Yes, I don't currently have it publicly available anywhere at the moment.

**Comment by ninrod** [comment]
all right thanks.
