### ISSUE TITLE
[FYI] Latest Master build of Qutebrowser has per domain settings!

### ISSUE THREAD

**Issue by Yousuf-Khurshid** [noctuid/dotfiles#6]
In case if you haven't revisited qutebrowser in a while, there has been some serious progress: 

https://github.com/qutebrowser/qutebrowser/blob/master/doc/changelog.asciidoc

The implementation is not finished yet and there are some issues: https://github.com/qutebrowser/qutebrowser/issues/3622

However, it looks ready enough to start playing around with.

Btw, I love your dotfiles and documentation and it was hugely influential on me adopting tiling window managers and Arch Linux (though I personally switched to i3).

**Comment by noctuid** [comment]
Thanks. I'm subscribed to most of the big issues and am using qutebrowser occasionally but am still primarily using firefox. Qutebrowser is a lot faster for me than firefox/pentadactyl and the completion is better among other things, but it has too many (often minor) annoyances for me to switch completely. Greasemonkey support is another recent change that will probably make qutebrowser more usable for me. I'm more interested in per-domain keybindings than settings, so hopefully that will be added soon as well.
