### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by mdsx** [noctuid/dotfiles#7]
Hi noctuid,

As the title says this isn't really an issue, I just wanted to show my appreciation for this incredible repo (and several others) you've created! I've been using bspwm since last summer and your dotfiles and extensive documentation have proved invaluable from first learning about bspwm to trying to implement fancier and fancier things with it. Also though I don't aim to create a (nearly) mouse-less workflow, it's still awesome to see the ways you've gone about trying to achieve it. 

Sorry I didn't know how else to message you, feel free to close this issue whenever :)

**Comment by noctuid** [comment]
Thanks, glad it helped!
